#! /bin/sh

sxhkd &
xrandr --output Virtual1 --mode 1920x1080 &
compton --config /home/sbsiete/.config/compton/compton.conf &
feh --bg-fill /home/sbsiete/Imágenes/wallpaper.jpg &
~/.config/polybar/shapes/launch.sh &
wmname LG3D &
~/.config/polybar/launch.sh &

bspc config pointer_modifier mod1

bspc monitor Virtual1 -d 1 2 3 4 5 6 7 

bspc config border_width         0
bspc config window_gap          16


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating
